// Brizy Protogen TypeScript Package
// Generated protobuf types for Brizy platform
// This file is auto-generated by bin/createRootFile.sh

// Brizy message types
export * from '../gen/brizy_pb';

// Cloud message types
export * from '../gen/cloud_pb';

// Doctrine message types
export * from '../gen/doctrine_pb';

// Message message types
export * from '../gen/message_pb';

// Notification message types
export * from '../gen/notification_pb';

// Translation message types
export * from '../gen/translation_pb';

// Re-export protobuf utilities that might be useful
export { create, fromBinary, toBinary, fromJson, toJson } from '@bufbuild/protobuf';
export { type Any, anyPack, anyIs } from "@bufbuild/protobuf/wkt";
